# Generated by Django 2.2.7 on 2019-11-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendahs', '0003_producto_descuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precioPromocion',
        ),
        migrations.AddField(
            model_name='producto',
            name='precioAntes',
            field=models.IntegerField(default=0, verbose_name='Precio Antes'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioVenta',
            field=models.IntegerField(default=0, verbose_name='Precio de Venta'),
        ),
    ]
