# Generated by Django 2.2.7 on 2019-11-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendahs', '0004_auto_20191128_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='medioPago',
            field=models.CharField(default='Contra entrega', max_length=120, verbose_name='Medio de pago'),
        ),
    ]
