# Generated by Django 2.2.7 on 2019-11-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendahs', '0005_producto_mediopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tiempoEntrega',
            field=models.CharField(default='2 días máximo', max_length=120, verbose_name='Tiempo de entrega'),
        ),
    ]
